// Generated by CoffeeScript 1.4.0
(function() {
  var CategoryStars, LanguageGraph, LanguageGraphMatrix, SelectableStar, myStar, myStars,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  LanguageGraph = (function() {

    function LanguageGraph(width, height) {
      this.width = width;
      this.height = height;
      this.container = "#viz";
      this.x_column = "cpu(s)";
      this.y_column = "size(B)";
      this.average = this.rollup('lang', 'mean');
      this.best = this.rollup('name', 'min');
      this.scaleX = d3.scale.sqrt().domain([0, 5000]).rangeRound([0, this.width]);
      this.scaleY = d3.scale.sqrt().domain([1, 6]).rangeRound([this.height, 0]);
    }

    LanguageGraph.prototype.lang = function(d) {
      return d.lang;
    };

    LanguageGraph.prototype.getX = function(d) {
      return d[this.x_column];
    };

    LanguageGraph.prototype.getY = function(d) {
      return d[this.y_column];
    };

    LanguageGraph.prototype.x = function() {
      var t;
      t = this;
      return function(d) {
        return t.getX(d);
      };
    };

    LanguageGraph.prototype.y = function() {
      var t;
      t = this;
      return function(d) {
        return t.getY(d);
      };
    };

    LanguageGraph.prototype.setX = function(d, x) {
      return d[this.x_column] = x;
    };

    LanguageGraph.prototype.setY = function(d, y) {
      return d[this.y_column] = y;
    };

    LanguageGraph.prototype.getX0 = function(d) {
      return this.scaleX(this.getX(d));
    };

    LanguageGraph.prototype.getY0 = function(d) {
      return this.scaleY(this.getY(d));
    };

    LanguageGraph.prototype.rect = function(c) {
      return c.append("rect").attr("width", this.width).attr("height", this.height);
    };

    LanguageGraph.prototype.rollup = function(k, f) {
      return d3.nest().key(function(d) {
        return d[k];
      }).rollup(this.rollupFunction(f));
    };

    LanguageGraph.prototype.rollupFunction = function(f) {
      var t;
      t = this;
      return function(v) {
        var m;
        m = {};
        t.setX(m, d3[f](v, t.x()));
        t.setY(m, d3[f](v, t.y()));
        return m;
      };
    };

    LanguageGraph.prototype.initialize = function(data) {
      this.setData(data);
      this.clean();
      this.relativize();
      return this.doAverage();
    };

    LanguageGraph.prototype.setData = function(data) {
      return this.data = data;
    };

    LanguageGraph.prototype.clean = function() {
      var d, _i, _len, _ref, _results;
      _ref = this.data;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        d = _ref[_i];
        this.setX(d, parseFloat(this.getX(d)));
        _results.push(this.setY(d, parseFloat(this.getY(d))));
      }
      return _results;
    };

    LanguageGraph.prototype.relativize = function() {
      var d, mins, _i, _len, _ref, _results;
      mins = this.best.map(this.data);
      _ref = this.data;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        d = _ref[_i];
        this.setX(d, this.getX(d) / this.getX(mins[d.name]));
        _results.push(this.setY(d, this.getY(d) / this.getY(mins[d.name])));
      }
      return _results;
    };

    LanguageGraph.prototype.doAverage = function() {
      return this.averages = this.average.map(this.data);
    };

    LanguageGraph.prototype.drawStar = function(focus) {
      var star;
      star = focus.append("g").classed("star", function() {
        return true;
      }).attr("transform", this.centerStar());
      return this.drawLines(star);
    };

    LanguageGraph.prototype.centerStar = function() {
      var t;
      t = this;
      return function(d) {
        var avg;
        avg = t.averages[d.lang];
        return "translate(" + (t.getX0(avg)) + "," + (t.getY0(avg)) + ")";
      };
    };

    LanguageGraph.prototype.drawLines = function(star) {
      var t;
      t = this;
      return star.selectAll("path").data(this.benchmarksForLanguage()).enter().append("path").attr("d", this.spoke());
    };

    LanguageGraph.prototype.benchmarksForLanguage = function() {
      var lang_benches;
      lang_benches = d3.nest().key(function(d) {
        return d.lang;
      }).map(this.data);
      return function(d) {
        return lang_benches[d.lang];
      };
    };

    LanguageGraph.prototype.spoke = function() {
      var t;
      t = this;
      return function(d) {
        var avg, cx, cy;
        avg = t.averages[d.lang];
        cx = t.getX0(d) - t.getX0(avg);
        cy = t.getY0(d) - t.getY0(avg);
        return "M 0 0 L " + cx + " " + cy;
      };
    };

    LanguageGraph.prototype.drawBorder = function(focus) {
      return this.rect(focus).classed('border', function() {
        return true;
      });
    };

    return LanguageGraph;

  })();

  LanguageGraphMatrix = (function(_super) {

    __extends(LanguageGraphMatrix, _super);

    function LanguageGraphMatrix(w, h) {
      if (w == null) {
        w = 40;
      }
      if (h == null) {
        h = 40;
      }
      LanguageGraphMatrix.__super__.constructor.call(this, w, h);
      this.row_count = 5;
      this.languagesByX.key(this.x());
      this.languagesByY.key(this.y());
    }

    LanguageGraphMatrix.prototype.flatten = function(lng, avg) {
      var m;
      m = {};
      m.lang = lng;
      this.setX(m, this.getX(avg));
      this.setY(m, this.getY(avg));
      return m;
    };

    LanguageGraphMatrix.prototype.flattenAverages = function() {
      var avg, lng;
      return this.flat_averages = (function() {
        var _ref, _results;
        _ref = this.averages;
        _results = [];
        for (lng in _ref) {
          avg = _ref[lng];
          _results.push(this.flatten(lng, avg));
        }
        return _results;
      }).call(this);
    };

    LanguageGraphMatrix.prototype.languagesByX = d3.nest().sortKeys(function(a, b) {
      return d3.ascending(parseFloat(a), parseFloat(b));
    });

    LanguageGraphMatrix.prototype.languagesByY = d3.nest().sortKeys(function(a, b) {
      return d3.descending(parseFloat(a), parseFloat(b));
    });

    LanguageGraphMatrix.prototype.matrixValues = function(cols) {
      var cell, col, _i, _len, _results;
      _results = [];
      for (_i = 0, _len = cols.length; _i < _len; _i++) {
        col = cols[_i];
        _results.push((function() {
          var _j, _len1, _results1;
          _results1 = [];
          for (_j = 0, _len1 = col.length; _j < _len1; _j++) {
            cell = col[_j];
            _results1.push(cell.values[0]);
          }
          return _results1;
        })());
      }
      return _results;
    };

    LanguageGraphMatrix.prototype.languagesByXThenY = function() {
      var byX, chunk, col, cols, end, i;
      chunk = this.row_count;
      byX = this.languagesByX.entries(this.flat_averages);
      end = function(i) {
        return Math.min(byX.length - 1, i + chunk);
      };
      cols = (function() {
        var _i, _ref, _results;
        _results = [];
        for (i = _i = 0, _ref = byX.length; 0 <= _ref ? _i <= _ref : _i >= _ref; i = _i += chunk) {
          _results.push(byX.slice(i, end(i)));
        }
        return _results;
      })();
      cols = this.matrixValues(cols);
      return this.matrixValues((function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = cols.length; _i < _len; _i++) {
          col = cols[_i];
          _results.push(this.languagesByY.entries(col));
        }
        return _results;
      }).call(this));
    };

    LanguageGraphMatrix.prototype.layoutColumns = function() {
      return d3.select(this.container).selectAll(".col").data(this.languagesByXThenY()).enter().append("div").classed("col", function() {
        return true;
      });
    };

    LanguageGraphMatrix.prototype.layoutCells = function(col) {
      return smallMultiples(col, {
        width: this.width,
        height: this.height,
        data: function(d) {
          return d;
        },
        margin: {
          left: 40,
          right: 40,
          top: 10,
          bottom: 10
        },
        title: {
          size: 10,
          padding: 5,
          data: this.lang
        }
      });
    };

    LanguageGraphMatrix.prototype.createLayout = function() {
      return this.layoutCells(this.layoutColumns());
    };

    LanguageGraphMatrix.prototype.draw = function(data) {
      var focus;
      this.initialize(data);
      this.flattenAverages();
      focus = this.createLayout();
      return this.render(focus);
    };

    LanguageGraphMatrix.prototype.render = function(focus) {
      this.drawStar(focus);
      return this.drawBorder(focus);
    };

    return LanguageGraphMatrix;

  })(LanguageGraph);

  SelectableStar = (function(_super) {

    __extends(SelectableStar, _super);

    function SelectableStar(w, h) {
      if (w == null) {
        w = 250;
      }
      if (h == null) {
        h = 250;
      }
      SelectableStar.__super__.constructor.call(this, w, h);
    }

    SelectableStar.prototype.createCanvas = function() {
      return this.canvas = smallMultiples(d3.select(this.container), {
        width: this.width,
        height: this.height,
        margin: {
          left: 10,
          right: 10,
          top: 10,
          bottom: 10
        }
      });
    };

    SelectableStar.prototype.selectLanguage = function(lang) {
      return this.canvas.datum({
        lang: lang
      });
    };

    SelectableStar.prototype.drawDots = function(focus) {
      var t;
      t = this;
      return focus.selectAll(".benchmark").data(this.data).enter().append("circle").classed("benchmark", function() {
        return true;
      }).attr("r", 1.5).attr("fill", "#d88").attr("opacity", .6).attr("transform", function(d) {
        if (isNaN(t.getX(d || isNaN(t.getY(d))))) {
          return;
        }
        return "translate(" + (t.getX0(d)) + "," + (t.getY0(d)) + ")";
      });
    };

    SelectableStar.prototype.drawList = function() {
      var a, t;
      t = this;
      return d3.select(this.container).append("ul").selectAll("li").data((function() {
        var _results;
        _results = [];
        for (a in this.averages) {
          _results.push(a);
        }
        return _results;
      }).call(this)).enter().append("li").text(function(d) {
        return d;
      }).on("mouseover", function(d) {
        t.selectLanguage(d);
        t.canvas.select('.star').remove();
        return t.drawStar(t.canvas);
      });
    };

    SelectableStar.prototype.draw = function(data) {
      var focus;
      this.initialize(data);
      focus = this.createCanvas();
      this.selectLanguage("JavaScript V8");
      this.drawDots(focus);
      this.drawStar(focus);
      return this.drawList();
    };

    return SelectableStar;

  })(LanguageGraph);

  myStar = new SelectableStar();

  myStar.container = "#selectable";

  d3.csv("data.csv", function(data) {
    return myStar.draw(data);
  });

  CategoryStars = (function(_super) {

    __extends(CategoryStars, _super);

    function CategoryStars() {
      return CategoryStars.__super__.constructor.apply(this, arguments);
    }

    CategoryStars.prototype.typeColor = d3.scale.ordinal().domain(['imperative', 'oo', 'functional', 'scripting']).range(['#6da', '#97e', '#fe7', '#fa7']);

    CategoryStars.prototype.background = function() {
      var t;
      t = this;
      return function(d) {
        return t.typeColor(types[d.lang]);
      };
    };

    CategoryStars.prototype.drawBackground = function(focus) {
      return this.rect(focus).attr("fill", this.background());
    };

    CategoryStars.prototype.render = function(focus) {
      this.drawBackground(focus);
      return CategoryStars.__super__.render.call(this, focus);
    };

    return CategoryStars;

  })(LanguageGraphMatrix);

  myStars = new CategoryStars;

  myStars.container = "#categories";

  d3.csv("data.csv", function(data) {
    return myStars.draw(data);
  });

}).call(this);
