# my categorization of the language types

types = {
  'C gcc':                  'imperative'
  'Pascal Free Pascal':     'imperative'
  'Go':                     'imperative'
  'Fortran Intel':          'imperative'
  'C++ g++':                'oo'
  'Scala':                  'oo'
  'Smalltalk VisualWorks':  'oo'
  'Ada 2005 GNAT':          'oo'
  'Java 7':                 'oo'
  'C# Mono':                'oo'
  'Dart':                   'oo'
  'ATS':                    'functional'
  'OCaml':                  'functional'
  'F# Mono':                'functional'
  'Erlang HiPE':            'functional'
  'Lisp SBCL':              'functional'
  'Haskell GHC':            'functional'
  'Clojure':                'functional'
  'Racket':                 'functional'
  'Lua':                    'scripting'
  'PHP':                    'scripting'
  'Python 3':               'scripting'
  'Ruby 2.0':               'scripting'
  'JavaScript V8':          'scripting'
  'Ruby JRuby':             'scripting'
  'Perl':                   'scripting'
}
